-- 今天吃啥 Supabase schema
-- 运行位置：Supabase Dashboard -> SQL Editor -> New query

create table if not exists public.shops (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('red','black')),
  loc text not null check (loc in ('online','offline')),
  product text not null default '店铺整体',
  status text not null default 'approved' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.reasons (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public.shops(id) on delete cascade,
  text text not null,
  likes integer not null default 0 check (likes >= 0),
  dislikes integer not null default 0 check (dislikes >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public.shops(id) on delete cascade,
  text text not null,
  status text not null default 'approved' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.app_admins (
  user_id uuid primary key,
  created_at timestamptz not null default now()
);

create index if not exists shops_status_created_idx on public.shops(status, created_at desc);
create index if not exists reasons_shop_id_idx on public.reasons(shop_id);
create index if not exists comments_shop_id_status_idx on public.comments(shop_id, status);

alter table public.shops enable row level security;
alter table public.reasons enable row level security;
alter table public.comments enable row level security;
alter table public.app_admins enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.app_admins
    where user_id = auth.uid()
  );
$$;

drop policy if exists "read approved shops" on public.shops;
create policy "read approved shops"
  on public.shops for select
  using (status = 'approved' or public.is_admin());

drop policy if exists "submit shops" on public.shops;
create policy "submit shops"
  on public.shops for insert
  with check (status in ('pending','approved'));

drop policy if exists "admin update shops" on public.shops;
create policy "admin update shops"
  on public.shops for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "read reasons for visible shops" on public.reasons;
create policy "read reasons for visible shops"
  on public.reasons for select
  using (
    exists (
      select 1 from public.shops
      where shops.id = reasons.shop_id
        and (shops.status = 'approved' or public.is_admin())
    )
  );

drop policy if exists "insert reasons for submitted shops" on public.reasons;
create policy "insert reasons for submitted shops"
  on public.reasons for insert
  with check (
    exists (
      select 1 from public.shops
      where shops.id = reasons.shop_id
        and shops.status in ('pending','approved')
    )
  );

drop policy if exists "read approved comments for visible shops" on public.comments;
create policy "read approved comments for visible shops"
  on public.comments for select
  using (
    (status = 'approved' or public.is_admin())
    and exists (
      select 1 from public.shops
      where shops.id = comments.shop_id
        and (shops.status = 'approved' or public.is_admin())
    )
  );

drop policy if exists "insert public comments" on public.comments;
create policy "insert public comments"
  on public.comments for insert
  with check (status = 'approved');

drop policy if exists "admins read themselves" on public.app_admins;
create policy "admins read themselves"
  on public.app_admins for select
  using (auth.uid() = user_id);

create or replace function public.increment_reason_vote(reason_id bigint, vote_type text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if vote_type = 'l' then
    update public.reasons set likes = likes + 1 where id = reason_id;
  elsif vote_type = 'd' then
    update public.reasons set dislikes = dislikes + 1 where id = reason_id;
  else
    raise exception 'invalid vote_type: %', vote_type;
  end if;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select, insert on public.shops to anon, authenticated;
grant select, insert on public.reasons to anon, authenticated;
grant select, insert on public.comments to anon, authenticated;
grant execute on function public.increment_reason_vote(bigint, text) to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;

-- 如果需要审核入口：
-- 1. 先打开网页，让它匿名登录一次。
-- 2. 到 Supabase Dashboard -> Authentication -> Users 找到你的 user id。
-- 3. 把 YOUR_USER_ID 替换后运行：
-- insert into public.app_admins(user_id) values ('YOUR_USER_ID')
-- on conflict (user_id) do nothing;

do $$
begin
  alter publication supabase_realtime add table public.shops;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.reasons;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.comments;
exception when duplicate_object then null;
end $$;
